"""
analyzer.py — GPT-4o failure analysis with circuit breaker.

The system prompt is tuned to read and interpret:
  - stderr / error_trace  (Python/Scala/SQL stack traces)
  - stdout / logs         (print() output, spark.show(), progress logs)
  - per-task state_message (Databricks task-level error summaries)
  - pipeline event messages (DLT Spark exceptions)
"""
from __future__ import annotations

import json
import logging
import time
from dataclasses import dataclass, field
from typing import Dict

from openai import OpenAI
from config import Config

logger = logging.getLogger(__name__)


_SYSTEM = """
You are a senior Databricks Platform Reliability Engineer with deep expertise
in Apache Spark, Delta Live Tables, PySpark, Scala, and SQL.

Your job is to read raw Databricks job/pipeline failure output — including
stderr stack traces, stdout logs, task error messages, and pipeline events —
and produce a precise root-cause diagnosis.

════════════════════════════════════════════════════════
HOW TO READ THE LOGS
════════════════════════════════════════════════════════

STDERR / error_trace
  - Look for the LAST exception in the traceback — that is the root cause.
  - Common patterns:
      AnalysisException      → schema mismatch, missing column/table, bad SQL
      PermissionDenied       → bad credentials, missing Unity Catalog grants
      ClassNotFoundException → missing library / wrong cluster runtime
      java.io.FileNotFound   → source path does not exist or wrong mount
      OutOfMemoryError       → cluster too small, skewed data, missing cache
      TimeoutException       → upstream dependency slow, cluster auto-scaling lag
      StreamingQueryException → DLT/Structured Streaming logic error
      py4j.Py4JJavaError     → PySpark wrapping a Java exception — read the cause
  - Ignore the outer wrapper — find the innermost "Caused by:" line.

STDOUT / logs
  - Print statements and spark.show() output appear here.
  - Row counts, schema prints, checkpoint info — all useful signals.
  - A sudden stop in stdout mid-pipeline means the error occurred at that step.
  - Look for WARNING or ERROR lines from Python logging.

TASK-LEVEL state_message
  - Each failed task has a short Databricks-generated summary.
  - This is usually the best single-line description of the failure.
  - "Driver stopped" → OOM or uncaught exception on driver.
  - "Cluster terminated" → spot instance reclaimed or auto-termination.
  - "Exit code: 1" → user script exited non-zero (check stdout for reason).

PIPELINE EVENTS (DLT)
  - error.exceptions[].message contains the full Spark stack trace.
  - event.message is a human-readable summary generated by Databricks.
  - Flow name in origin tells you which DLT table failed.

════════════════════════════════════════════════════════
ACTION DECISION RULES
════════════════════════════════════════════════════════
Apply ONLY when you have actual error text. Do NOT guess.

  retry   → Transient / infrastructure issues:
              cluster startup failure, spot reclaim, network timeout,
              OOM (if single occurrence), throttling (HTTP 429),
              "Cluster terminated unexpectedly"

  repair  → Partial job failure:
              multi-task job where only SOME tasks failed,
              upstream task data is still valid,
              error is deterministic but isolated to one task

  escalate → Code / data / config bugs that retry will NOT fix:
              AnalysisException, PermissionDenied, FileNotFound,
              ClassNotFoundException, schema mismatch, assertion errors,
              NullPointerException in user code, bad SQL syntax,
              missing Unity Catalog table, wrong mount path

  ignore  → Expected non-failure:
              test / dev / cancelled run, known flaky job marked ignore,
              zero-row result that is intentional

════════════════════════════════════════════════════════
STRICT RULES
════════════════════════════════════════════════════════
- If error details are empty or unavailable → confidence=low, action=escalate.
- NEVER guess a transient error when no error text is provided.
- Base every field ONLY on what appears in the logs below.
- config_changes must be a concrete fix (e.g. "Add READ privilege on
  hive_metastore.bronze.events to the service principal") not generic advice.

Respond ONLY with this JSON (no markdown, no preamble):
{
  "root_cause": "<one sentence — name the exact exception/error>",
  "recommended_action": "retry | repair | escalate | ignore",
  "reasoning": "<2-3 sentences citing specific lines from the logs>",
  "config_changes": "<concrete fix or empty string>",
  "confidence": "high | medium | low"
}
""".strip()


@dataclass
class Analysis:
    root_cause: str
    recommended_action: str   # retry | repair | escalate | ignore
    reasoning: str
    config_changes: str
    confidence: str
    raw: Dict = field(default_factory=dict)

    @classmethod
    def safe_escalate(cls, reason: str) -> "Analysis":
        return cls(
            root_cause=reason,
            recommended_action="escalate",
            reasoning="Analysis unavailable — defaulting to escalate for human review.",
            config_changes="",
            confidence="low",
        )


class Analyzer:
    _OPEN_THRESHOLD = 5
    _RESET_AFTER = 300  # seconds

    def __init__(self, cfg: Config) -> None:
        self._client = OpenAI(api_key=cfg.openai_api_key)
        self._model = cfg.openai_model
        self._failures = 0
        self._opened_at = 0.0

    def analyze(self, failure: Dict) -> Analysis:
        if self._circuit_open():
            return Analysis.safe_escalate("LLM circuit breaker open")

        prompt = self._build_prompt(failure)

        # Visible preview of what is being sent so you can debug extraction
        stderr_preview = (failure.get("error_trace") or "")[:120].replace("\n", " ")
        stdout_preview = (failure.get("stdout_logs") or "")[:80].replace("\n", " ")
        error_preview  = (failure.get("error") or "")[:120].replace("\n", " ")
        logger.info(
            "  Sending to LLM | key=%s\n"
            "    error   : %s\n"
            "    stderr  : %s\n"
            "    stdout  : %s",
            failure.get("failure_key", "?"),
            error_preview  or "⚠️ empty",
            stderr_preview or "⚠️ empty",
            stdout_preview or "⚠️ empty",
        )

        # Full prompt at DEBUG level for deeper investigation
        logger.debug("Full LLM prompt:\n%s", prompt)

        try:
            resp = self._client.chat.completions.create(
                model=self._model,
                messages=[
                    {"role": "system", "content": _SYSTEM},
                    {"role": "user",   "content": prompt},
                ],
                temperature=0.1,   # lower = more deterministic, less hallucination
                response_format={"type": "json_object"},
                timeout=30,
            )
            data = json.loads(resp.choices[0].message.content or "{}")
            self._failures = 0

            a = Analysis(
                root_cause=data.get("root_cause", "unknown"),
                recommended_action=self._valid(data.get("recommended_action", "escalate")),
                reasoning=data.get("reasoning", ""),
                config_changes=data.get("config_changes", ""),
                confidence=data.get("confidence", "medium"),
                raw=data,
            )
            logger.info("LLM → %s (%s) | %s", a.recommended_action, a.confidence, a.root_cause)
            return a

        except Exception as e:
            self._failures += 1
            if self._failures >= self._OPEN_THRESHOLD:
                self._opened_at = time.time()
            logger.error("OpenAI error: %s", e)
            return Analysis.safe_escalate(str(e))

    def _circuit_open(self) -> bool:
        if self._failures < self._OPEN_THRESHOLD:
            return False
        if time.time() - self._opened_at >= self._RESET_AFTER:
            self._failures = 0
            return False
        return True

    @staticmethod
    def _valid(action: str) -> str:
        return action if action in {"retry", "repair", "escalate", "ignore"} else "escalate"

    @staticmethod
    def _build_prompt(f: Dict) -> str:
        """
        Build a structured prompt with clearly labelled sections so GPT-4o
        can parse each log type independently and cite specific lines.
        Empty sections are omitted entirely — no blank headers.
        """
        def _section(title: str, content: str, limit: int = 3000) -> str:
            content = content.strip()
            if not content:
                return ""
            if len(content) > limit:
                content = content[:limit] + "\n...[truncated]"
            return f"\n{'─' * 56}\n{title}\n{'─' * 56}\n{content}"

        header = (
            f"Failure type : {f.get('type', 'unknown').upper()}\n"
            f"Name         : {f.get('name', 'unknown')}\n"
            f"Job/Pipeline : {f.get('pipeline_id') or f.get('job_id', '')}\n"
            f"Run/Update   : {f.get('update_id') or f.get('run_id', '')}\n"
            f"Run URL      : {f.get('run_url', '')}"
        )

        # Build each log section — only include non-empty ones
        sections = "".join(filter(None, [
            _section("TASK ERROR MESSAGES  (state_message per failed task)",
                     f.get("error", ""), 2000),
            _section("STDERR / STACK TRACE  (error_trace — innermost exception is root cause)",
                     f.get("error_trace", ""), 3000),
            _section("STDOUT / LOGS  (print output, spark.show(), logging statements)",
                     f.get("stdout_logs", ""), 2000),
            _section("NOTEBOOK OUTPUT",
                     f.get("notebook_output", ""), 1000),
        ]))

        if not sections.strip():
            sections = (
                "\n⚠️  NO LOG OUTPUT AVAILABLE\n"
                "The token may lack 'jobs' read permission, or this job type\n"
                "does not expose logs via the runs/get-output API.\n"
                "Set confidence=low and recommended_action=escalate."
            )

        return header + "\n" + sections
